- hosts: bastion
  remote_user: kovbasa
  become: yes
  become_method: sudo
  tasks:

    - name: copy key
      copy:
        src: /home/kovbasa/.ssh/id_rsa
        dest: /home/kovbasa/.ssh/
        owner: kovbasa
        group: kovbasa
        mode: 0600

    - name: copy key.pub
      copy:
        src: /home/kovbasa/.ssh/id_rsa.pub
        dest: /home/kovbasa/.ssh/
        owner: kovbasa
        group: kovbasa
        mode: 0644

    - name: copy ansible files
      copy:
        src: /home/kovbasa/ansible/
        dest: /home/kovbasa/ansible/
        owner: kovbasa
        group: kovbasa
        mode: preserve

    - name: install ansible
      apt:
        update_cache: yes
        name: ansible
        state: latest

