- hosts: elasticsearch
  remote_user: kovbasa
  become: yes
  become_method: sudo
  
  tasks:
    - name: Install reqs for Docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add the GPG key for Docker
      shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

    - name: Add the repository
      shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

    - name: Update and install docker
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install the Docker module for Python
      pip:
        name: docker

    - name: Create container
      docker_container:
        name: "Elasticsearch"
        image: "bitnami/elasticsearch:latest"
        ports:
        - "9200:9200"
        - "9300:9300"
        env:
            ELASTICSEARCH_CLUSTER_NAME=netology
            xpack.security.enrollment.enabled=true
        state: started
      
