- hosts: webservers
  remote_user: kovbasa
  become: yes
  become_method: sudo
  tasks:
    - name: copy filebeat.deb
      copy:
        src: /home/kovbasa/ansible/filebeat-8.6.2-amd64.deb
        dest: /home/kovbasa
    - name: install filebeat
      apt:
        deb: "/home/kovbasa/filebeat-8.6.2-amd64.deb"
    - name: replace config file
      copy:
        src: /home/kovbasa/ansible/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
    - name: setup filebeat
      shell: 'filebeat setup'
    - service:
       name: filebeat
       state: started
