- hosts: kibana
  remote_user: kovbasa
  become: yes
  become_method: sudo
  vars:
    elasticsearch_ip: "{{ groups['elasticsearch'] | map('extract', hostvars, ['inventory_hostname']) | join ('') }}"
  roles:
    - kibana
